train_input:
        batch_size: 100

val_input:
        batch_size: 100

model:
        name: "vit_attempt"
        mixed_precision: True

optimizer:
        optimizer_type: "SGD"
        learning_rate: 0.001
        momentum: 0.9
        loss_scaling_factor: 1.0

runconfig:
        autogen_policy: "aggressive"
        max_steps: 10000
        checkpoint_steps: 2000
        log_steps: 50
        seed: 1
        save_losses: True
