train_input:
    batch_size: 4

val_input:
    batch_size: 4

model:
    name: "vit"
    in_channels: 3
    patch_size: 16
    emb_size: 768
    img_size: 224
    depth: 3
    num_heads: 12
    num_classes: 1000
    mixed_precision: True

optimizer:
    optimizer_type: "SGD"
    learning_rate: 0.001
    momentum: 0.9
    loss_scaling_factor: 1.0

runconfig:
    autogen_policy: "medium"
    max_steps: 10000
    checkpoint_steps: 2000
    log_steps: 50
    seed: 1
    save_losses: True
