train_input:
        data_dir: "/software/cerebras/dataset/fc_mnist/data/mnist/train"
        batch_size: 128
        drop_last_batch: True
        shuffle: True
        to_float16: True

eval_input:
        data_dir: "/software/cerebras/dataset/fc_mnist/data/mnist/val"
        batch_size: 128
        drop_last_batch: True
        to_float16: True

model:
        name: "ViT_mnist"
        mixed_precision: True
        patch_size: 7
        hidden_dim: 64
        num_heads: 4
        num_layers: 2
        dropout: 0.0
        activation_fn: "relu"

optimizer:
        optimizer_type: "SGD"
        learning_rate: 0.001
        momentum: 0.9
        loss_scaling_factor: 1.0

runconfig:
        max_steps: 10000
        checkpoint_steps: 2000
        log_steps: 50
        seed: 1
        save_losses: True
        
